server {
    listen 80;
    server_name ton-domaine.fr www.ton-domaine.fr;

    root /var/www/mbprestige/public;
    index index.php index.html;

    access_log /var/log/nginx/mbprestige_access.log;
    error_log /var/log/nginx/mbprestige_error.log;

    client_max_body_size 50M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php-fpm.sock;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
